Update content

diff --git a/.github/workflows/checkov_scan.yaml b/.github/workflows/checkov_scan.yaml
--- a/.github/workflows/checkov_scan.yaml
+++ b/.github/workflows/checkov_scan.yaml
@@ -50,7 +50,7 @@ jobs:
           framework: arm
           soft_fail: false
           output_format: sarif
-          output_file_path: results.sarif
+          output_file_path: "results-${{ github.run_id }}.sarif"
 
       - name: Run Checkov scan - junitxml
         if: inputs.code_scanning_enabled == 'false'
@@ -60,31 +60,31 @@ jobs:
           framework: arm
           soft_fail: false
           output_format: junitxml
-          output_file_path: ${{ github.workspace }}/results.xml
+          output_file_path: "results-${{ github.run_id }}.xml"
 
-      - name: Write sarif results
-        if: (success() || failure()) && inputs.code_scanning_enabled == 'true'
-        run: |
-          echo "$CHECKOV_RESULTS" > results.sarif
+      # - name: Write sarif results
+      #   if: (success() || failure()) && inputs.code_scanning_enabled == 'true'
+      #   run: |
+      #     echo "$CHECKOV_RESULTS" > results.sarif
 
-      - name: Write junitxml results
-        if: (success() || failure()) && inputs.code_scanning_enabled == 'true'
-        run: |
-          echo "$CHECKOV_RESULTS" > results.xml
+      # - name: Write junitxml results
+      #   if: (success() || failure()) && inputs.code_scanning_enabled == 'false'
+      #   run: |
+      #     echo "$CHECKOV_RESULTS" > results.xml
 
       - name: Upload results as artifact
         uses: actions/upload-artifact@v3
         if: success() || failure()
         with:
           name: scan-results
-          path: results.*
+          path: results-*
           retention-days: 10
 
       - name: Upload sarif file
         if: (success() || failure()) && inputs.code_scanning_enabled == 'true'
         uses: github/codeql-action/upload-sarif@v2
         with:
-          sarif_file: results.sarif
+          sarif_file: "results-${{ github.run_id }}.sarif"
           category: checkov
 
       - name: Publish scan results
@@ -92,5 +92,5 @@ jobs:
         uses: mikepenz/action-junit-report@v3
         with:
           check_name: Checkov Scan Results
-          report_paths: results.xml
+          report_paths: "results-${{ github.run_id }}.xml"
           detailed_summary: true
